### PR TITLE
readd lastest changes 

### PR DESCRIPTION
**Pull request by sergiomb2**
Hi , Richard , IMHO it is a good idea have a akmods repo , but you have ignored all my commits , I'm sending you again.

### CODE REVIEW

**Comment by hobbes1069** [comment]
Whoops... Yeah I didn't like managing all the source within RPM Fusion git. I'll take a look.

**Comment by sergiomb2** [comment]
Hi,  may I update akomds.spec in https://pkgs.rpmfusion.org/cgit/free/akmods.git/ 
remove files like : 

#Source0:        akmods
#Source1:        akmodsbuild
#Source2:        akmodsposttrans
#Source3:        akmods.service.in
#Source4:        akmods-shutdown
#Source5:        akmods-shutdown.service
#Source6:        akmods.h2m
#Source7:        95-akmods.preset

Second question why do you disable akmods-shutdown , now that I change the default timeout of systemd which is 90 seconds to 5 minutes ? 

Thanks .

**Comment by hobbes1069** [comment]
Yeah, I was considering removing the sources from RPM Fusion git but just hadn't made the decision yet.

I disabled akmods-shutdown by default because Nicolas doesn't like it and it wasn't worth fighting about. In some cases it can cause shutdown to hang while it completes.

**Comment by sergiomb2** [comment]
OK , so you are taking care of it ? , anyway,  we may talk over IRC ... , and we may work together  at same time, please join in #rpmfusion channel . 

Best regards.

**Comment by hobbes1069** [comment]
Yes, I'll work on a new release. I'll re-tag 0.5.6 since it was never built.

Work blocks IRC and probably not best for me to be on there while at work :)

**Comment by sergiomb2** [comment]
ok

**Pull request merged**
